version: "3.7"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk
    ports:
      #- external port:internal port
      - 8000:8000
      - 8088:8088
      - 8089:8089
      - 9997:9997
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    volumes:
      - ./output/TA-conf22:/opt/splunk/etc/apps/TA-conf22/